### ISSUE TITLE
ibctest fails with HTTP error on Arch Linux

### ISSUE THREAD

**Issue by makeworld-the-better-one** [strangelove-ventures/ibctest#153]
I am running on the latest commit, d906ad7.

After cloning, I ran `make ibctest` and then `./bin/ibctest`. I ran the second command twice, and both times the default tests failed with an HTTP error. Here is the console log for each.

First run: [run1.txt](https://github.com/strangelove-ventures/ibctest/files/8941769/run1.txt)  
Second run: [run2.txt](https://github.com/strangelove-ventures/ibctest/files/8941772/run2.txt)

I understand this project is still in active development, I'm filing this issue in hopes of learning more. Maybe this is a known ongoing bug, or something unexpected that we can hopefully fix. Thank you!

**Comment by DavidNix** [comment]
@makeworld-the-better-one this appears to be related to your docker setup.

What OS and docker version are you using? Can you describe your docker environment in detail?

**Comment by makeworld-the-better-one** [comment]
Thanks for the article. All those steps were familiar to me, except manually loading the `loop` kernel module. But doing that made no difference, the error result was still the same.

> Additionally, our previous Arch linux user suggestion looking at permissions. There may be a requirement to run as root or vice versa.

Since my user is part of the `docker` group, there shouldn't be any permission issues. I never have to use `sudo` with docker.

> We can investigate more if you'd like. However it may take several weeks as we work this into our sprints given other priorities.
>
> My suggested workaround is to use a distro other than Arch as you've demonstrated.

As an Arch user, I'm very curious why this is occurring, as AFAIK this should not be an area where Arch differs from other distros. Docker is supposed to solve this problem! So in that way I am definitely interested in what's causing this and the solution. But as a user of ibctest I don't have a problem anymore, as using a Debian VM/droplet is a fine solution for me. So don't worry about putting this on your team's plate, I don't want to take up your time when the issue is solvable on my end.

I'll leave this issue open though, let me know if you ever end up figuring this out. Thanks for all your help!
