### ISSUE TITLE
Extend chain interface to run arbitrary commands and return an output. 

### ISSUE THREAD

**Issue by DavidNix** [strangelove-ventures/ibctest#158]
## Problem

Per ibc-go's team:

> I was thinking maybe when iterating on tests it would be nice to have some hooks that allow for arbitrary command execution, since as we develop the features the commands might change before they're done. Ideally the interfaces get updated once the feature is released (but that's a bit of a chicken and egg scenario!)

So they're trying to test unreleased, new features. We wouldn't update the chain interface until those features are finalized. As cian mentions, those commands could change a lot before the final release.

**Comment by DavidNix** [comment]
> one other misc note: I noticed that the function dockerutil.HandleNodeJobError(exitCode, stdout, stderr, err) was not returning an error when I used the wrong command and was prompted with the help output

**Comment by mark-rushakoff** [comment]
There have been several times when I needed to debug a miswritten command, and I had to update `HandleNodeJobError` to include the stdout and stderr (the two ignored parameters to the function).

https://github.com/strangelove-ventures/ibctest/blob/8b23c0fa73fa956d7261b644fdbbf34e04bb585c/internal/dockerutil/errors.go#L5-L13

I am on the fence about including that detail by default, but it would probably be more helpful if it were included, so you could quickly see an error like `--foo is not a valid flag`.

**Comment by DavidNix** [comment]
These may be too cosmos-flavored, but you can reach node endpoints via these methods in `ibc.Chain`.

```
	// retrieves rpc address that can be reached by other containers in the docker network
	GetRPCAddress() string

	// retrieves grpc address that can be reached by other containers in the docker network
	GetGRPCAddress() string

	// GetHostRPCAddress returns the rpc address that can be reached by processes on the host machine.
	// Note that this will not return a valid value until after Start returns.
	GetHostRPCAddress() string

	// GetHostGRPCAddress returns the grpc address that can be reached by processes on the host machine.
	// Note that this will not return a valid value until after Start returns.
	GetHostGRPCAddress() string
```
