### ISSUE TITLE
Consider using ioutil.TempDir instead of t.TempDir to create home directories

### ISSUE THREAD

**Issue by chatton** [strangelove-ventures/ibctest#168]
`t.TempDir` removes the home directory upon test passing or failing. This means that if a test fails, it is difficult to exec into the containers to debug as the home dir has been removed. [ioutil.TempDir](https://pkg.go.dev/io/ioutil#TempDir) leaves it to the caller to remove the directory. 

I propose something along the lines of

```golang
home, err := ioutil.TempDir("", t.Name())
// handle err

defer func(){
   if !t.Failed(){
     // remove home dir
  }
}
```

This way we can still exec into the containers and debug upon test failure.

**Comment by mark-rushakoff** [comment]
Generally, I'm not in favor of this behavior by default. Tests should not leave ephemeral artifacts behind until someone opts in to them. 

When I get to the point that I am actively debugging a failing test involving files persisted to disk, I have a couple approaches in my toolbelt:

```go
// 1. Just reassign the directory.

home := t.TempDir()
home = "/tmp/testdebug" // Adding new statements here to make it simple
_ = os.RemoveAll(home)  // to remove them before I commit my changes.
_ = os.MkdirAll(home)

// 2. Log the directory and add a long sleep.

defer func() {
  t.Log(home) // Log the home directory as the last line for easy discovery.
  time.Sleep(time.Hour) // May need to ^Z or adjust -timeout test flag.
}()
```

I am usually fine with having to hand-edit the test to keep the artifacts around. But ibctest is a slightly different use case, as it is a library intended to be more widely used.

I would not be opposed to a standard helper that can be configured by the command line or an environment variable.

```go
func TempDir(t *testing.T) string {
  t.Helper()

  name := clean(t.Name()) // TODO: implement clean, see definition of (*testing.T).TempDir()
  dir, err := os.MkdirTemp("", name)
  if err != nil {
    t.Fatalf("TempDir: %v", err)
  }

  t.Cleanup(func() {
    if t.Failed() && keepTestingTempDir() { // TODO: implement keepTestingTempDir
      t.Logf("Leaving test temporary directory at %s", dir)
      return
    }
    _ = os.RemoveAll(dir)
  })
}
```

IMO the decision to make here is how to satisfy `keepTestingTempDir` in the above sample. It could be an either-or of an environment variable or a dedicated flag to the `ibctest` binary.

Side note, the `ioutil` package is deprecated, and `os.MkdirTemp` would be preferred here if we were to go that route.
