### ISSUE TITLE
Allow the ability to provide your own `builtinChainConfigs`

### ISSUE THREAD

**Issue by chatton** [strangelove-ventures/ibctest#175]
Currently there is a hard coded map of built in chain configs

```golang
var builtinChainConfigs = map[string]ibc.ChainConfig{
	"gaia":     cosmos.NewCosmosHeighlinerChainConfig("gaia", "gaiad", "cosmos", "uatom", "0.01uatom", 1.3, "504h", false),
	"osmosis":  cosmos.NewCosmosHeighlinerChainConfig("osmosis", "osmosisd", "osmo", "uosmo", "0.0uosmo", 1.3, "336h", false),
	"juno":     cosmos.NewCosmosHeighlinerChainConfig("juno", "junod", "juno", "ujuno", "0.0025ujuno", 1.3, "672h", false),
	"agoric":   cosmos.NewCosmosHeighlinerChainConfig("agoric", "agd", "agoric", "urun", "0.01urun", 1.3, "672h", true),
	"icad":     cosmos.NewCosmosHeighlinerChainConfig("icad", "icad", "cosmos", "photon", "0.00photon", 1.2, "504h", false),
	"penumbra": penumbra.NewPenumbraChainConfig(),
}
```

We are able to use `NewBuiltinChainFactory` which makes creating a ChainFactory very easy, but it would be nice to be able to specify our own `defaults`, something like 

`func NewChainFactory(log *zap.Logger, specs []*ChainSpec, builtIns map[string]ibc.ChainConfig) *BuiltinChainFactory`

to provide the easy of use and also our set of configs that are specific to our repo and our registries, and maybe don't belong in this particular builtins map.

**Comment by boojamya** [comment]
This should satisfy this use case: https://github.com/strangelove-ventures/ibctest/pull/294

Please re-open if not.
