### ISSUE TITLE
Override entry point in `Exec` function

### ISSUE THREAD

**Issue by chatton** [strangelove-ventures/ibctest#183]
Currently, the entry point is not overridden when creating a container to run a job. I encountered the following error

```bash
    reporter.go:226:
        	Error Trace:	testsuite.go:191
        	            				fee_middleware_test.go:287
        	Error:      	Received unexpected error:
        	            	failed to create faucet accounts: failed to create common account with name faucet: failed to create key with name "faucet" on chain simapp-a: exit code 1:  Error: unknown command "simd" for "simd"
        	            	Run 'simd --help' for usage.
```

The entrypoint to this specific container is `["simd"]`, as a result the command the ibctest builds is appended to this entrypoint.

I believe this should be solvable by just specifying an empty array for the entrypoint.
```golang
	Config: &docker.Config{
		Entrypoint: []string{},
                 // other fields
	},
```

**Comment by mark-rushakoff** [comment]
I touched a bit of this code while porting from dockertest to the Docker SDK. The use of `Entrypoint` was inconsistent. I think it is fine for us to use an explicitly empty entrypoint everywhere, based on how we are using Docker containers in ibctest.
