### ISSUE TITLE
ibctest.User/ibctest.RelayerWallet types could maybe be combined

### ISSUE THREAD

**Issue by charleenfei** [strangelove-ventures/ibctest#220]
the difference is seems to be only in use case of the type and not the type itself. 

for example, currently, we have to do things like this ```chainAWallet.Bech32Address(chainB.Config().Bech32Prefix)``` to get the bech32 address from a User type, but the RelayerWallet type offers it out of the box. just a little confusing as from the chain/SDK POV these could be the same account address types right?

**Comment by jackzampolin** [comment]
Thank you for the issue @charleenfei, that should be a relatively quick change.
