### ISSUE TITLE
Interchain Accounts methods use incorrect hostname.

### ISSUE THREAD

**Issue by chatton** [strangelove-ventures/ibctest#236]
Currently the ICA methods e.g. `RegisterInterchainAccount` use `tn.Name()` to reference the chain Node. this results in a no such host error

```bash
        	Error:      	Received unexpected error:
        	            	exit code 1:  Error: post failed: Post "http://node-0-chain-a-TestInterchainAccountsTestSuite_TestInterchainAccounts:26657": dial tcp: lookup node-0-chain-a-TestInterchainAccountsTestSuite_TestInterchainAccounts: no such host
```

Based on the other functions in the file, I think this should be `tn.HostName()`.

**Comment by chatton** [comment]
Hi @jtieri! I like the idea of removing it from the `Chain` interface to avoid it getting too large

I think a lot of non-core functionality could be exposed as functions from different packages, and simply depend on an interface that looked like

```golang
type Execer interface {
  Exec(ctx context.Context, cmd []string, env []string) (stdout, stderr []byte, err error)
}
```

I think it would still be extremely valuable to have this logic abstracted into a function somewhere, perhaps something like this.

```golang
package ibctestica

func RegisterAccount(execer Execer, params...) (string, error) {
  execer.Exec(...)
}

// ibctestica.RegisterAccount(chainA, params...)
```

This way we have useful packages when working in a specific domain, but don't need to bloat the `Chain` interface and force everybody else to implement them.

However for the use case of new features, before they are supported in ibctest, I think the between `Exec` and `BroadcastTx` we have everything we need! 

I would be hesitant to leave tests using `Exec` directly in the long term though. I would rather use Exec for new features as we develop then, then eventually refactor those calls to use a separate method that is easier to reason about.

**Comment by jtieri** [comment]
Opened up a new issue to expose domain specific functions via packages versus using the `Chain` interface. 

#225 will remove the ICA related functions from the `Chain` interface and then we can standardize these functions like Cian mentions above in a future PR.
