### ISSUE TITLE
Allow ability to provide arbitrary startup options to relayers

### ISSUE THREAD

**Issue by chatton** [strangelove-ventures/ibctest#239]
I am working on writing a test for Interchain Accounts,  in order to do this, the go relayer needs to be started with the `-p events` flag. 

It is currently not possible to specify arbitrary arguments, just the `pathName`.

It would be useful to be able to specify possibly a `map[string]string` of relayer flags.

**Comment by agouin** [comment]
This is possible with `RelayerOption` `StartupFlags`  https://github.com/strangelove-ventures/ibctest/pull/188

**Comment by chatton** [comment]
Perfect! Thanks for the info @agouin, I'll close this issue.
