### ISSUE TITLE
Add client configuration

### ISSUE THREAD

**Issue by colin-axner** [strangelove-ventures/ibctest#246]
I'd like to be able to call a `CreateClient()` function and pass in a configuration type to construct the client. A similar idea is used in our [unit testing package](https://github.com/cosmos/ibc-go/blob/main/testing/config.go#L1) on ibc-go

**Comment by colin-axner** [comment]
Looks like this is closed by #248! Thanks @boojamya, I'm currently working on writing a e2e test using this, so I appreciate the quick turnaround!

**Comment by boojamya** [comment]
Hey @colin-axner! No prob, but is this what you were asking for?

This allows the relayer to pass in create client options (only client trusting period in this PR). I thought you wanted to be able to pass in a a client_state.json from the chain. 
EX:
`gaiad tx ibc client create [path/to/client_state.json] [path/to/consensus_state.json]`

This PR only adds the ability to do something like:
`rly transact client src_chain_name dst_chain_name path_name --client-tp 508h`

**Comment by colin-axner** [comment]
I primarily needed this to test client recovery proposals. The approach I'm going with is to set a really low trusting period (1 second), wait for the client to expire and then update it with a client with a regular trusting period. 

It might be useful in the future to specify other fields like the trust level. I also wonder if the create client options should be more of an interface since there might be different configurations depending on the client you are creating. That's what I went with in the ibc-go [testing package](https://github.com/cosmos/ibc-go/blob/main/testing/config.go#L17). We just do a switch on the [client type](https://github.com/cosmos/ibc-go/blob/main/testing/config.go#L14). Though this functionality hasn't been useful to us yet since we mainly test our tendermint client in that package

**Comment by colin-axner** [comment]
Here's where I am using it https://github.com/cosmos/ibc-go/pull/2130
