### ISSUE TITLE
Expose cosmos chain codec

### ISSUE THREAD

**Issue by colin-axner** [strangelove-ventures/ibctest#260]
I've started using the new `modifyGenesis` function and have gone with the approach of unmarshalling the bytes into their respective structures rather than modifying the json blob directly. This is useful for setting fields which take values such as sdk.Coins. I've ran into the issue that the codec for the chain is not being exposed so I am required to duplicate the code in [newTestEncoding](https://github.com/strangelove-ventures/ibctest/blob/main/chain/cosmos/codec.go#L15). I think it makes sense to expose this code and/or add a function which generates a usable proto codec for unmarshaling types

I'd propose to start by making `newTestEncoding` to be public

**Comment by agouin** [comment]
Closed by #271
