### ISSUE TITLE
Rename repo from ibc-test-framework to ibctest

### ISSUE THREAD

**Issue by DavidNix** [strangelove-ventures/ibctest#56]
If ever exposed as a Go package, `ibc-test-framework` is quite long and I suspect most package consumers will end up aliasing the package name.

**Comment by agouin** [comment]
Definitely agree the name should be shortened. Might be cool to come up with a creative name like some of our other repos. Here is a word cloud from the Dr. Strangelove transcript for ideas.
![image](https://user-images.githubusercontent.com/6722152/166310988-c474b348-910f-4230-b54f-eb918fd0bb40.png)

Or maybe something simple like `lace` as in lacing things together

**Comment by DavidNix** [comment]
Ha, I know it's boring but I like `ibctest` over the others. It's short and clear. 

It's the old Go proverb:

> [Clear is better than clever.](https://www.youtube.com/watch?v=PAAkCSZUG1c&t=14m35s)

---

> Here is a word cloud from the Dr. Strangelove transcript for ideas.

Out of curiosity, how did you make this?

**Comment by DavidNix** [comment]
But, I do realize marketability has value, so a boring but clear name may not fit the bill.

**Comment by mark-rushakoff** [comment]
I'm completely in favor of a clear and direct name. `ibctest` makes a lot of sense, but if we use that name, we may need to rename or rearrange the existing `ibctest` package in the module.

**Comment by mark-rushakoff** [comment]
I think the files in the `ibctest` directory will just move to the new repository root, which will still be named `ibctest`.

**Comment by jackzampolin** [comment]
This sounds great! Love the rename.
