### ISSUE TITLE
Assert inclusion proof of packet data commitment in the outgoing chain's state

### ISSUE THREAD

**Issue by DavidNix** [strangelove-ventures/ibctest#90]
From the IBC spec on receiving packets: https://github.com/cosmos/ibc/blob/master/spec/core/ics-004-channel-and-packet-semantics/README.md#receiving-packets

> Checks the inclusion proof of packet data commitment in the outgoing chain's state

Namely, the chain should protect itself from a malicious relayer. 

This may be related to "misbehavior" as present in the IBC spec. However, as of this writing, misbehavior is not implemented in the go relayer.

**Comment by jtieri** [comment]
This is a good issue! Ideally we should get submitting misbehavior functionality added back to the relayer sooner than later so we can build out testing here like you suggest.

**Comment by DavidNix** [comment]
https://github.com/strangelove-ventures/ibctest/issues/20 duplicate?
